default_stages: [pre-commit]
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff  # run the linter
        types_or: [ python, pyi ]  # avoid running on Jupyter Notebooks
        args: [ --fix ]
      - id: ruff-format  # run the formatter
        types_or: [ python, pyi ]  # avoid running on Jupyter Notebooks
