name: Deploy to EC2 using ssh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Create known_hosts file
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${EC2_HOST} >> ~/.ssh/known_hosts
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}

      - name: Write SSH key to file
        run: |
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy code to EC2
        run: |
          ssh -i ~/.ssh/private_key ${USER}@${EC2_HOST} <<'EOF'
          cd ~/code/backtesting-app
          git reset --hard HEAD
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl stop backtesting_app
          sudo systemctl start backtesting_app
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          WORKDIR: ${{ secrets.WORKDIR }}
          USER: ${{ secrets.USER }}
