name: Deploy to EC2 using ssh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Create known_hosts file
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${EC2_HOST} >> ~/.ssh/known_hosts
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}

      - name: Write SSH key to file
        run: |
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Upload .env to EC2
        run: |
          echo COINMARKETCAP_API_KEY=${COINMARKETCAP_API_KEY} >> .env
          scp -i ~/.ssh/private_key .env ${USER}@${EC2_HOST}:${WORKDIR}
        env:
          COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          WORKDIR: ${{ secrets.WORKDIR }}
          USER: ${{ secrets.USER }}

      - name: Deploy code to EC2
        run: |
          ssh -i ~/.ssh/private_key ${USER}@${EC2_HOST} <<-EOF
          cd ${WORKDIR}
          git reset --hard HEAD
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart backtesting-app
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          WORKDIR: ${{ secrets.WORKDIR }}
          USER: ${{ secrets.USER }}
